
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *
import ctypes

ctypes.windll.shcore.SetProcessDpiAwareness(1)


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x500")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    527.4769287109375,
    249.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    260.0,
    500.0,
    fill="#FFFFFF",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    130.0,
    250.0,
    image=image_image_2
)

canvas.create_text(
    26.0,
    354.0,
    anchor="nw",
    text="Povleci in spusti datoteke",
    fill="#333333",
    font=("Montserrat Medium", 16 * -1)
)

canvas.create_rectangle(
    260.0,
    0.0,
    262.0,
    500.0,
    fill="#D9D9D9",
    outline="")
window.resizable(False, False)
window.mainloop()